# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-11 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('recording_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(blank=True, null=True)),
                ('recording_path', models.CharField(blank=True, max_length=10000, null=True)),
                ('transcripts_path', models.CharField(blank=True, max_length=10000, null=True)),
                ('comments', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrum.Team')),
            ],
        ),
        migrations.AddField(
            model_name='recording',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrum.Team'),
        ),
    ]
